# Build
src: src

dest: client
assets: <%= site.dest %>/assets


# Site metadata
title: Hans McmUrdy Portfolio
lead: false
description: >
  "Foundation Blog theme and boilerplate, for Assemble."

# License info
license:
  type: MIT License
  url: ./license/index.html

# URLs
blog: http://hansuxdev.github.io/Foundation-Blog
repo: https://github.com/HansUXdev/Foundation-Blog
download:
  source: <%= site.repo %>/archive/master.zip


# SEO/SEM
google_analytics: false
google_site_id:   false


# Comments
disqus:
  shortname: foundationassembleblog


# Social
social:
  twitter:
    via: jonschlinkert
    username: assemble
  facebook: false
  gplus: false
  hn: false
  google: false


# Sharing
social:
  twitter: false
  facebook: false
  gplus: false
  hn: false
  google: false
